
ALTER TABLE player_saves
  ADD COLUMN IF NOT EXISTS kpi_failed_terms INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_event_chain_key TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS network_value INTEGER NOT NULL DEFAULT 0;
