-- 恩师系统
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS mentor_name TEXT NOT NULL DEFAULT '';
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS mentor_rank_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS mentor_faction TEXT NOT NULL DEFAULT '';
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS mentor_acquired_day INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS mentor_promoted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS mentor_relation INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS mentor_last_contact_day INTEGER NOT NULL DEFAULT 0;

-- 门生系统（rank≥12解锁）
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS protege_name TEXT NOT NULL DEFAULT '';
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS protege_rank_level INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS protege_ability INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS protege_loyalty INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS protege_invest_days INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS protege_last_act_day INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS protege_promoted_day INTEGER NOT NULL DEFAULT 0;

-- 组织部暗线多目标（JSON数组，最多3个潜伏目标）
ALTER TABLE player_saves ADD COLUMN IF NOT EXISTS org_insider_targets TEXT NOT NULL DEFAULT '[]';