
ALTER TABLE game_saves
  ADD COLUMN IF NOT EXISTS gray_income_total INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS investigation_day INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS investigation_evidence_level INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS parent_status TEXT NOT NULL DEFAULT 'healthy',
  ADD COLUMN IF NOT EXISTS gray_income_cooldowns TEXT NOT NULL DEFAULT '{}';
