
-- 接班人系统字段
ALTER TABLE game_saves
  ADD COLUMN IF NOT EXISTS successor_id TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS successor_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS successor_faction TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS successor_school TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS successor_rank_level INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS successor_ability INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS successor_loyalty INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS successor_invest_days INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS successor_last_act_day INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS game_over_verdict TEXT DEFAULT NULL;

-- 家庭成员增加双规牵连标记
ALTER TABLE family_members
  ADD COLUMN IF NOT EXISTS career_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS block_reason TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS block_severity TEXT NOT NULL DEFAULT '';
