ALTER TABLE player_saves
  ADD COLUMN IF NOT EXISTS professional_rank_level INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS grassroots_exp_years INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS special_assess_score INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS democratic_eval_score INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS slot_wait_years INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_demo_eval_day INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_special_assess_day INTEGER NOT NULL DEFAULT 0;