ALTER TABLE player_saves
  ADD COLUMN IF NOT EXISTS route_vote_result TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS route_vote_day INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS honor_level INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS honor_day INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS memoir_written BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS memoir_style TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS memoir_influence INTEGER NOT NULL DEFAULT 0;